let shopItemsData = [{
    id: "jfhgbvnscs",
    name: "Ko'ylak",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Ofis Ko'ylagi",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Futbolka",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Kostyum",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Galstug",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Tufli",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Qora Kostyum",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Polo Ko'ylak",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Jinsi Ko'ylak",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Jinsi Shim",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Kepka",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Charm Etik",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-12.png",
  },
];